name: Add Update Label Weekly

# Runs at 7:00 UTC / 0:00 PDT (midnight) every Friday, excluding July and December
# CUSTOMIZE: Adjust cron to your project's schedule
on:
  schedule:
    - cron: '0 7 * 1-6,8-11 5'
  workflow_dispatch:

# Set defaults for GITHUB_TOKEN 
permissions:  
  contents: read  
  issues: read

jobs:
  Add-Update-Label-to-Issues-Weekly:
    runs-on: ubuntu-latest
    # CUSTOMIZE: Update to match project repo name
    if: github.repository == 'hackforla/PROJECT_REPO'
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/github-script@v8
        with:
          # CUSTOMIZE: Update with project token, needs "repo" & "project" scopes
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            const script = require('./github-actions/add-update-label-weekly/add-label.js');
            script({ github, context });
